using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering;

public class CamResolution : MonoBehaviour
{
     void start()
    {
        

    }

    void Update()
    {
        Camera cam = GetComponent<Camera>();

        // 카메라 컴포넌트의 Viewport Rect
        Rect rt = cam.rect;

        //현재 세로 모드 9 : 19
        float scale_height = ((float)Screen.width / Screen.height) / ((float)9 / 19);
        float scale_width = 1f / scale_height;

        if (scale_height < 1)
        {
            rt.height = scale_height;
            rt.y = (1f - scale_height) / 2f;

        }
        else
        {
            rt.width = scale_width;
            rt.x = (1f - scale_width) / 2f;
        }

        cam.rect = rt;

        
        
    }



    void OnPreCull() => GL.Clear(true, true, Color.black);

}
